image: golang:1.9

stages:
  - build
  - test

stages:
  - build
  - test

before_script:
  - mkdir -p artifacts
  - go get github.com/superhawk610/bar
  - go get github.com/aws/aws-sdk-go/aws
  - go get github.com/aws/aws-sdk-go/aws/session
  - go get github.com/aws/aws-sdk-go/service/ebs
  - go get github.com/superhawk610/bar
  - go get github.com/aws/aws-sdk-go/service/ec2

build-projectname:
  stage: build
  script:
    - find . -name "*.go" 
    - find . -name "*.go" |xargs -I% go build  -o $(echo  %|sed 's/.go/.nix') %
    - cp *.nix artifacts
  artifacts:
    paths:
      - artifacts