image: golang:1.9

stages:
  - build
  - test

stages:
  - build
  - test

build-binaries:
  stage: build
  script:
    - mkdir -p artifacts
    - go get github.com/superhawk610/bar
    - go get github.com/aws/aws-sdk-go/aws
    - go get github.com/aws/aws-sdk-go/aws/session
    - go get github.com/mattn/go-isatty
    - go get github.com/aws/aws-sdk-go/service/ebs
    - go get github.com/superhawk610/bar
    - go get github.com/aws/aws-sdk-go/service/ec2
    - find . -name "*.go" 
    - find . -name "*.go" |xargs -I% bash build.sh %
    - ls -la
  artifacts:
    paths:
      - artifacts

test-data:
  stage: test
  script:
    - go get -u github.com/golang/lint/golint
    - /go/bin/golint *.go